### ISSUE TITLE
Resources.

### ISSUE THREAD

**Issue by dawnfreelance** [Small-JS/SmallJS#13]
Hello,

I know this is for issues, please don't hate me for posting here.

I was wondering if there was something i could use a guidance to learn and write SmallJS?
I am in the process of learning JS, and know a bit of smalltalk. i tried emailing info@small-js.org but was denied.

**Comment by FunctionPoint** [comment]
Hi there Dawn (?), I'm glad you reacted here.
I've just checked the email address and it works form me,
so I would very much like to hear what error you are getting.
You can contact me on my real email: richard ronteltap at hotmail dot com
without spaces and with an at sign and a dot character of course. 

On the SmallJS website there is a page for learning resources:
https://small-js.org/Learning/Learning.html
If you need more, please let me know.

Cheers, Richard

**Comment by FunctionPoint** [comment]
Now in direct contact with issue creator, so this can be closed.
