### ISSUE TITLE
Examples: Pharo support

### ISSUE THREAD

**Issue by FunctionPoint** [Small-JS/SmallJS#18]
Make an example app with a SmallJS browser front-end and a Pharo back-end.
Communication will be done through regular web API calls,
so no framework expansions will be needed on either side.
And the Pharo side, something like Seaside will have to be preloaded.
.
It will just be a showcase that gives existing Pharo developers a quick start option,
if they want to consider using SmallJS as a native front-end, 
as an alternative to using bridgeing functionality, e.g. PharoJS.

**Comment by MichaelKentBurns** [comment]
Awesome idea.  Just what I'm looking for.
I'm working on a Pharo model of a Study Bible and want to front end it with web apps written by my budding web programmers.     I want to prototype the front end in ST to interact with the actual data model back end in Pharo.  Then have the students write various frontends using their usual HTML, CSS, JS tools and knowledge.

**Comment by FunctionPoint** [comment]
Great to hear, Michael, it would indeed be ideal for (starting) web developers
get starting expericience with Smalltalk. 
Cheers, Richard

**Comment by FunctionPoint** [comment]
It's done :-)
